apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  source:
    path: HelmCharts/live/longhorn
    repoURL: https://github.com/milindsidhu/Projects.git
    targetRevision: dev/MS
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
destination:
  namespace: longhorn-system
  server: https://kubernetes.default.svc
source:
  path: HelmCharts/live/longhorn
  repoURL: https://github.com/milindsidhu/Projects.git
  targetRevision: dev/MS
sources: []
project: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
