apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-siem-explorer.fullname" . }}-backend
  labels:
    {{- include "splunk-siem-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
