apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-siem-explorer.fullname" . }}-frontend
  labels:
    {{- include "splunk-siem-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
