apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-siem-explorer.fullname" . }}-secret
  labels:
    {{- include "splunk-siem-explorer.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secret.postgresPassword | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:%d/%s" .Values.postgresql.username .Values.secret.postgresPassword (include "splunk-siem-explorer.fullname" .) (.Values.postgresql.service.port | int) .Values.postgresql.database | b64enc | quote }}
