{{- if .Values.createPatchJob.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-patcher
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-patcher-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: secret-patcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-docker-secret-annotation
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '1'
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: patcher
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - >
              kubectl patch secret my-registry-secret -n default
              --type=merge
              -p '{"metadata":{"annotations":{"replicator.v1.mittwald.de/replicate-to":"{{ join "," (concat .Values.regulatedNoSANamespaces (keys .Values.appNamespaces)) }}"}}}'
---
{{- end }}