apiVersion: v1
kind: Service
metadata:
  name: backstage-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backstage-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
