apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: backstage
  ports:
    - port: {{ .Values.backstage.port }}
      targetPort: {{ .Values.backstage.port }}
      nodePort: {{ .Values.backstage.nodePort }}
