apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      All containers in pods within namespaces labeled
      policy-scope=enforced must define CPU and memory limits.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-resource-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaceSelector:
              matchLabels:
                policy-scope: enforced
      exclude:
        any:
        - resources:
            namespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            - argocd
            - kyverno
            - cert-manager
            - cloudflared
            - local-path-storage
            - actions-runner-system
            # - metallb
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        message: "CPU and memory limits are required for all containers."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"