apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-lab.fullname" . }}-control
  labels:
    {{- include "splunk-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-panel
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: control-panel
  type: {{ .Values.controlPanel.service.type }}
  ports:
    - port: {{ .Values.controlPanel.service.port }}
      targetPort: 80
