apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-lab.fullname" . }}-nginx-conf
  labels:
    {{- include "splunk-lab.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /generator/ {
            proxy_pass http://{{ include "splunk-lab.fullname" . }}-generator:{{ .Values.loadGenerator.service.port }}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 60s;
        }

        location /target/ {
            proxy_pass http://{{ include "splunk-lab.fullname" . }}-target:{{ .Values.targetApp.service.port }}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 60s;
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    }
