{{- if .Values.fluentBit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-lab.fullname" . }}-fluent-bit
  labels:
    {{- include "splunk-lab.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-lab.fullname" . }}-fluent-bit
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "splunk-lab.fullname" . }}-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "splunk-lab.fullname" . }}-fluent-bit
subjects:
  - kind: ServiceAccount
    name: {{ include "splunk-lab.fullname" . }}-fluent-bit
    namespace: {{ .Release.Namespace }}
{{- end }}
