apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-lab.fullname" . }}-generator
  labels:
    {{- include "splunk-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-generator
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: load-generator
  ports:
    - port: {{ .Values.loadGenerator.service.port }}
      targetPort: 8001
