apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-lab.fullname" . }}-target
  labels:
    {{- include "splunk-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: target-app
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: target-app
  ports:
    - port: {{ .Values.targetApp.service.port }}
      targetPort: 8000
