apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-controller
spec:
  destination:
    namespace: lang-app
    server: https://kubernetes.default.svc
  source:
    path: HelmCharts/live/namespaceController
    repoURL: https://github.com/milindsidhu/Projects.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
destination:
  namespace: lang-app
  server: https://kubernetes.default.svc
source:
  path: HelmCharts/live/namespaceController
  repoURL: https://github.com/milindsidhu/Projects.git
  targetRevision: main
sources: []
project: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true