# list of namespaces to be managed by the operator
namespaces:
  # - default
  # - lang-app
  - cloudflared
  - monitoring
  - metallb
  - ingress-nginx
  - actions-runner-system
  # - backstage
  - cert-manager
  - external-secrets
  - mittwald-replicator
  - mlflow
  - kyverno
  - istio-system

  
createPatchJob:
  enabled: true

roleRules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "jobs", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "delete", "watch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete"]
  # - apiGroups: ["kopf.dev"]
  #   resources: ["secretreplicators"]
  #   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

readSecretsRole:
  enabled: false
  # clusterRules:
  #   - apiGroups: [""]
  #     resources: ["secrets"]
  #     verbs: ["get", "list", "watch"]
  #   - apiGroups: ["apiextensions.k8s.io"]
  #     resources: ["customresourcedefinitions"]
  #     verbs: ["get", "list", "watch"]
    # - apiGroups: ["kopf.dev"]
    #   resources: ["secretreplicators"]
    #   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    # - apiGroups: [""]
    #   resources: ["events"]
    #   verbs: ["create", "patch", "update"]
    # - apiGroups: [""]
    #   resources: ["namespaces"]
    #   verbs: ["get", "list", "watch"]

##### Unused values, kept for reference for SecretReplicator operator #####

cleanupKopfFinalizer:
  enabled: false

postSyncJob:
  enabled: false

secretReplicator:
  enabled: false
#   crd:
#     name: secretreplicators.kopf.dev
#     group: kopf.dev
#     plural: secretreplicators
#     singular: secretreplicator
#     kind: SecretReplicator
#     shortNames:
#       - sr
#       - srep
#     # scope: Namespaced
#     scope: Cluster
#     version: v1
#     requiredSpecFields:
#       - sourceNamespace
#       - sourceSecretName
#       - targetSecretName
#   deployment:
#     name: secret-replicator
#     replicas: 1
#     labels:
#       app: secret-replicator
#     image:
#       repository: milindsidhu/secret-replicator
#       tag: v1.0.1
#       pullPolicy: IfNotPresent
#       pullSecretName: my-registry-secret
#     env:
#       LOG_LEVEL: info
#       METRICS_ENABLED: "true"
#   secretReplicatorCR:
#     name: secret-replicator-cr
#     spec:
#       sourceNamespace: default
#       sourceSecretName: my-registry-secret
#       targetSecretName: my-docker-secret