apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name | quote }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | quote }}
      role: {{ .Values.aws.iamRole | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
            namespace: external-secrets