{{- if .Values.testSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.testSecret.name | quote }}
  namespace: {{ .Values.testSecret.namespace | quote }}
spec:
  refreshInterval: {{ .Values.testSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.testSecret.name | quote }}
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.testSecret.remoteKey | quote }}
{{- end }}