apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  access-key: {{ .Values.aws.credentials.accessKey | quote }}
  secret-access-key: {{ .Values.aws.credentials.secretAccessKey | quote }}