######
# Create a certificate using the method in folder - "/Projects/Kubernetes_manifests/cert-manager"
# This will help create a single Certificate per namespace
######

apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-api
  namespace: lang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner-api
  template:
    metadata:
      labels:
        app: runner-api
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: runner-api
        image: milindsidhu/fast-api-runner:v1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: runner-api
  namespace: lang-app
spec:
  selector:
    app: runner-api
  ports:
  - port: 80
    targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner-api
  namespace: lang-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - runner-api<domain>
    secretName: langapp-cert-self-secret
  rules:
  - host: runner-api<domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: runner-api
            port:
              number: 80
