apiVersion: v2
name: eso-operator
description: Installs External Secrets Operator via upstream Helm chart
type: application
version: 0.1.0
appVersion: "0.20.4"
dependencies:
  - name: external-secrets
    version: 0.20.4
    repository: https://charts.external-secrets.io
