{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Name }}
    secrets.io/managed: "true"
    policy-scope: enforced
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ . }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Name }}
---
{{- end }}