{{- if and .Values.readSecretsRole.enabled (gt (len .Values.namespaces) 0) }}

# ClusterRole to read secrets (created once)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-secret-clusterrole
rules:
{{- toYaml .Values.readSecretsRole.clusterRules | nindent 2 }}

{{- range $ns := .Values.namespaces }}

---
# RoleBinding in the default namespace to bind ClusterRole to the namespace's SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-sa-{{ $ns }}
  namespace: {{ $ns }}
subjects:
  - kind: ServiceAccount
    name: sa-{{ $ns }}
    namespace: {{ $ns }}
roleRef:
  kind: ClusterRole
  name: read-secret-clusterrole
  apiGroup: rbac.authorization.k8s.io
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $ns }}-clusterrolebinding-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-secret-clusterrole
subjects:
- kind: ServiceAccount
  name: sa-{{ $ns }}
  namespace: {{ $ns }}

{{- end }}
{{- end }}
