{{- if .Values.replication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.replication.secretName }}
  namespace: {{ .Values.namespace }}
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ .Values.replication.sourceNamespace }}/{{ .Values.replication.sourceSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
{{- end }}
