# {{- if .Values.tunnels.k8sApi.enabled }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: cloudflared-config
#   namespace: cloudflared
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#   labels:
#     app: cloudflared
#     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
# data:
#   config.yaml: |
#     tunnel: PENDING
#     credentials-file: /etc/cloudflared/credentials.json
#     ingress:
#       - hostname: {{ .Values.tunnels.k8sApi.hostname }}
#         service: {{ .Values.tunnels.k8sApi.service }}
#         originRequest:
#           noTLSVerify: {{ .Values.tunnels.k8sApi.noTLSVerify }}
#       - service: http_status:404
# {{- end }}
# ---
# {{- if .Values.tunnels.ssh.enabled }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ssh-cloudflared-config
#   namespace: cloudflared
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#   labels:
#     app: ssh-cloudflared
#     chart: {{ .Chart.Name }}-{{ .Chart.Version }}
# data:
#   config.yaml: |
#     tunnel: PENDING
#     credentials-file: /etc/cloudflared/credentials.json
#     ingress:
#       - hostname: {{ .Values.tunnels.ssh.hostname }}
#         service: {{ .Values.tunnels.ssh.service }}
#       - service: http_status:404
# {{- end }}