apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repo-runners
  namespace: actions-runner-system

spec:
  template:
    metadata:
      labels:
        app: gha-runner
        env: prod

    spec:
      repository: milindsidhu/Projects

      imagePullSecrets:
        - name: my-registry-secret

      nodeSelector:
        kubernetes.io/hostname: linux-master

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: runner
          image: milindsidhu/actions-runner-kics:v2.1.20
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
