apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/my-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K