apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - |
          while true; do echo -e "HTTP/1.1 200 OK\n\nHey User! You did it." | nc -l -p 8080; done
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  namespace: default
spec:
  selector:
    app: busybox-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: busybox-ingress
  namespace: default
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: busybox<domain>
    external-dns.alpha.kubernetes.io/target: edf03371-7be3-4673-aeae-4baf7c76fd57.cfargotunnel.com
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - busybox<domain>
  #   secretName: multi-cert-self-secret 
  rules:
  - host: busybox<domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: busybox-service
            port:
              number: 80
